"""
render/docx_renderer.py — python-docx renderer for Advisory and Executive Summary.
Produces a styled DOCX with heading hierarchy, body text, and a provenance table.
"""
from __future__ import annotations
import pathlib
import uuid
from datetime import datetime

from app.core.schemas import ContentPlan, GeneratedOutput, RenderedArtifact
from app.render.base import MIME_TYPES
from app.core.logging import get_logger

logger = get_logger(__name__)

try:
    from docx import Document
    from docx.shared import Pt, Inches, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    _DOCX = True
except ImportError:
    _DOCX = False


class DocxRenderer:
    def __init__(self, output_format: str = "advisory") -> None:
        self.output_format = output_format
        self.mime_type = MIME_TYPES.get(output_format,
            "application/vnd.openxmlformats-officedocument.wordprocessingml.document")

    def render(
        self,
        plan: ContentPlan,
        output: GeneratedOutput,
        artifact_dir: pathlib.Path,
    ) -> RenderedArtifact:
        if not _DOCX:
            return self._stub(output, artifact_dir,
                              "python-docx not installed: pip install python-docx")

        doc = Document()

        # Document properties
        core = doc.core_properties
        core.author = "Sutra — SIH26154"
        core.title = self.output_format.replace("_", " ").title()

        # Default style
        style = doc.styles["Normal"]
        style.font.name = "Noto Sans"
        style.font.size = Pt(10.5)

        # Title
        title_para = doc.add_heading(
            self.output_format.replace("_", " ").upper(), level=0)
        title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

        doc.add_paragraph(
            f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}  |  "
            f"Language: {output.language}  |  "
            f"Lock: {output.lock_hash[:16] if output.lock_hash else 'n/a'}..."
        ).runs[0].font.size = Pt(8)

        doc.add_paragraph("")  # spacer

        # Sections
        for section in output.sections:
            if not section.claims:
                continue
            doc.add_heading(section.section_key.replace("_", " ").title(), level=1)
            for claim in section.claims:
                p = doc.add_paragraph(style="List Bullet")
                p.text = claim.text
                # Footnote-style citation
                if claim.fact_ids:
                    run = p.add_run(f" [{', '.join(claim.fact_ids)}]")
                    run.font.size = Pt(7)
                    run.font.color.rgb = RGBColor(0x88, 0x88, 0x88)

        doc.add_paragraph("")
        doc.add_paragraph(
            "This document was generated by the Sutra AI platform. "
            "All claims are traceable to the locked Source of Truth. "
            f"Lock hash: {output.lock_hash or 'n/a'}"
        ).runs[0].font.size = Pt(8)

        filename = f"{self.output_format}_{output.output_id[:8]}.docx"
        file_path = artifact_dir / filename
        artifact_dir.mkdir(parents=True, exist_ok=True)
        doc.save(str(file_path))

        logger.info("DOCX rendered", format=self.output_format, path=str(file_path))
        return RenderedArtifact(
            artifact_id=str(uuid.uuid4()),
            output_id=output.output_id,
            output_format=self.output_format,
            file_path=str(file_path),
            mime_type=self.mime_type,
            size_bytes=file_path.stat().st_size,
            rendered_at=datetime.utcnow(),
        )

    def _stub(self, output: GeneratedOutput,
              artifact_dir: pathlib.Path, msg: str) -> RenderedArtifact:
        filename = f"{self.output_format}_{output.output_id[:8]}_stub.txt"
        file_path = artifact_dir / filename
        artifact_dir.mkdir(parents=True, exist_ok=True)
        file_path.write_text(f"[STUB] {msg}\n\n" +
                              "\n".join(c.text for s in output.sections
                                        for c in s.claims), encoding="utf-8")
        return RenderedArtifact(
            artifact_id=str(uuid.uuid4()),
            output_id=output.output_id,
            output_format=self.output_format,
            file_path=str(file_path),
            mime_type="text/plain",
            size_bytes=file_path.stat().st_size,
            rendered_at=datetime.utcnow(),
        )


def advisory_renderer() -> DocxRenderer:
    return DocxRenderer("advisory")


def executive_summary_renderer() -> DocxRenderer:
    return DocxRenderer("executive_summary")
