"""
render/html_renderer.py — HTML/CSS renderer for the Infographic format.
Uses Jinja2 + embedded CSS. Playwright can then screenshot it for layout checks.
Keeps HTML self-contained (inline styles) so it renders identically offline.
"""
from __future__ import annotations
import pathlib
import uuid
from datetime import datetime

from app.core.schemas import ContentPlan, GeneratedOutput, RenderedArtifact
from app.render.base import MIME_TYPES
from app.core.logging import get_logger

logger = get_logger(__name__)

_INFOGRAPHIC_TEMPLATE = """<!DOCTYPE html>
<html lang="{lang}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Infographic</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Noto+Sans:wght@400;700&display=swap');
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    font-family: 'Noto Sans', Arial, sans-serif;
    background: #0f172a; color: #f8fafc;
    width: 800px; min-height: 600px; padding: 40px;
  }}
  .headline {{ font-size: 2rem; font-weight: 700; color: #38bdf8;
               margin-bottom: 24px; line-height: 1.2; }}
  .stats-row {{ display: flex; gap: 20px; margin-bottom: 28px; flex-wrap: wrap; }}
  .stat-box {{
    background: #1e293b; border-radius: 12px; padding: 20px 24px;
    flex: 1; min-width: 180px;
  }}
  .stat-value {{ font-size: 2rem; font-weight: 700; color: #f59e0b; }}
  .stat-label {{ font-size: 0.85rem; color: #94a3b8; margin-top: 4px; }}
  .point {{ background: #1e293b; border-left: 4px solid #38bdf8;
             padding: 14px 18px; margin-bottom: 12px; border-radius: 0 8px 8px 0; }}
  .source-note {{ font-size: 0.75rem; color: #475569; margin-top: 24px; }}
  .lock-badge {{
    display: inline-block; background: #064e3b; color: #6ee7b7;
    font-size: 0.7rem; padding: 3px 8px; border-radius: 4px; margin-top: 12px;
  }}
</style>
</head>
<body>
{body}
<div class="lock-badge">&#128274; Locked SoT: {lock_hash_short}</div>
<div class="source-note">Generated by Sutra &mdash; SIH26154. All claims verified against locked Source of Truth.</div>
</body>
</html>"""


class HtmlRenderer:
    output_format = "infographic"
    mime_type = MIME_TYPES["infographic"]

    def render(
        self,
        plan: ContentPlan,
        output: GeneratedOutput,
        artifact_dir: pathlib.Path,
    ) -> RenderedArtifact:
        body_parts = []
        stats = []
        points = []

        for section in output.sections:
            key = section.section_key
            claims_text = " ".join(c.text for c in section.claims)
            if "stat" in key:
                if "|" in claims_text:
                    parts = claims_text.split("|", 1)
                    val = parts[0].strip()
                    lbl = parts[1].strip()
                else:
                    val = claims_text[:24]
                    lbl = key.replace("_", " ").title()
                stats.append((lbl, val))
            elif key == "headline":
                body_parts.insert(0,
                    f'<div class="headline">{claims_text}</div>')
            elif key == "source_note":
                pass  # rendered separately
            else:
                points.append(claims_text)

        if stats:
            stat_html = '<div class="stats-row">'
            for label, val in stats:
                stat_html += (
                    f'<div class="stat-box">'
                    f'<div class="stat-value">{val}</div>'
                    f'<div class="stat-label">{label}</div>'
                    f'</div>'
                )
            stat_html += "</div>"
            body_parts.append(stat_html)

        for pt in points:
            body_parts.append(f'<div class="point">{pt}</div>')

        body = "\n".join(body_parts)
        lock_short = (output.lock_hash[:16] + "...") if output.lock_hash else "n/a"

        html = _INFOGRAPHIC_TEMPLATE.format(
            lang=output.language,
            body=body,
            lock_hash_short=lock_short,
        )

        filename = f"infographic_{output.output_id[:8]}.html"
        file_path = artifact_dir / filename
        artifact_dir.mkdir(parents=True, exist_ok=True)
        file_path.write_text(html, encoding="utf-8")

        logger.info("HTML infographic rendered", path=str(file_path))
        return RenderedArtifact(
            artifact_id=str(uuid.uuid4()),
            output_id=output.output_id,
            output_format=self.output_format,
            file_path=str(file_path),
            mime_type=self.mime_type,
            size_bytes=file_path.stat().st_size,
            rendered_at=datetime.utcnow(),
        )
